### PR TITLE
support max.message.bytes

### PR DESCRIPTION
**Pull request by lordcheng10**
support max.message.bytes

### CODE REVIEW

**Comment by BewareMyPower** [comment]
Could you add a test?

**Comment by lordcheng10** [comment]
> Could you add a test?

I added the corresponding test, PTAL, thanks! @BewareMyPower e
In addition, is there a command like pulsar "/pulsarbot run-failure-checks"

**Comment by BewareMyPower** [comment]
> In addition, is there a command like pulsar "/pulsarbot run-failure-checks"

Currently not.

**Comment by lordcheng10** [comment]
> > In addition, is there a command like pulsar "/pulsarbot run-failure-checks"
> 
> Currently not.

OK，TBR，thanks!  @BewareMyPower

**Review by BewareMyPower — APPROVED** [review]

**Pull request merged**
