### PR TITLE
Only set the policy when the kafka metadata namespace is first created

### LINKED ISSUE #1143: [BUG] Retention Policy is resetted when restarting Pulsar-Broker with KoP
Describe the bug
When Pulsar-Broker is restarted in a Cluster, the Retention Policy will be resetted for public/default (or possibly the Namespace where Kafka on Pulsar will use)

To Reproduce

    Set Retention Policy:
    bin/pulsar-admin namespaces set-retention public/default --size 11G --time 1h

    Show Retention Policy:
    bin/pulsar-admin namespaces policies public/default
    ...
    "retention_policies" : {
    "retentionTimeInMinutes" : 60,
    "retentionSizeInMB" : 11264
    },
    ...

    Restart Pulsar Broker
    bin/pulsar-daemon stop broker
    bin/pulsar-daemon start broker

    Check Policies again
    bin/pulsar-admin namespaces policies public/default
    ...
    "retention_policies" : {
    "retentionTimeInMinutes" : 4320,
    "retentionSizeInMB" : -1
    },
    ...
    Expected behavior
    The retention policy should not be changed at all.

"retention_policies" : {
"retentionTimeInMinutes" : 60,
"retentionSizeInMB" : 11264
},

Screenshots

Desktop (please complete the following information):
CentOS 7
Pulsar 2.9.1

Additional context

### PR DESCRIPTION
**Pull request by wenbingshen**
Fixes #1143 
Master Issue: #1143 

### Modifications
As the title. Only set the policy when the kafka metadata namespace is first created.

### Documentation

Check the box below.

Need to update docs? 
  
- [x] `no-need-doc`

### CODE REVIEW

**Review by BewareMyPower — COMMENTED** [review]
Could you add a test to verify the policy is only set on the metadata namespace?

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by wenbingshen** [comment]
> Could you add a test to verify the policy is only set on the metadata namespace?

Sorry, it's been a long time, I'll add a test this week.

**Comment by wenbingshen** [comment]
@BewareMyPower Sorry for the long delay due to my personal reasons, I have now added a test to verify that the policy will only be set to the metadata namespace. PTAL.

**Review by BewareMyPower — APPROVED** [review]

**Pull request merged**
