### PR TITLE
auto split  if batch size > 4096

### LINKED ISSUE #218: [BUG] caught IllegalArgumentException if batch size > 4096
**Describe the bug**
caught IllegalArgumentException if batch size > 4096

**To Reproduce**
1. create a new topic --- t2
2. producer message with `batch size 5000`
`./rdkafka_performance -P -t t2 -b 127.0.0.1:9092 -s 128 -a 1 -X batch.num.messages=5000 -c 1000000`
3. consume
`./rdkafka_performance -C -t t2 -b 127.0.0.1:9092 -G g2`

**Expected behavior**
consume correctly

**Screenshots**
image

### PR DESCRIPTION
**Pull request by dockerzhang**
fixes #218

there is a 4096 batch size limit due to `MessageIdUtils` design for offset, this PR intends to auto split for size > 4096, we can use it before the offset refactor finished.

### CODE REVIEW

**Comment by BewareMyPower** [comment]
Could you add a test when a large batch was sent?

**Comment by dockerzhang** [comment]
@BewareMyPower I will add a UT later.

**Comment by BewareMyPower** [comment]
The tests failure may be fixed after #293 , please rebase to master after it's merged.

**Comment by dockerzhang** [comment]
this PR could close if #297 will be merged.

**Comment by BewareMyPower** [comment]
Close this PR since #296 is merged.

**Pull request closed without merging**
