### PR TITLE
Optimize the way to get the controllerId to branch-2.8.2

### PR DESCRIPTION
**Pull request by wenbingshen**
As the title.

### CODE REVIEW

**Comment by BewareMyPower** [comment]
The tests might not be related to this PR, they also happened for branch-2.9.2, see https://github.com/streamnative/kop/runs/5331597530?check_suite_focus=true. @Demogorgon314 is investigating the failed tests currently. I'll rerun the test first.

**Comment by Demogorgon314** [comment]
The failed test was caused by apache/pulsar#12600, this PR changed behavior. Before this change, only tenant admin allow to list topic, after apache/pulsar#12600, it allows consume permission list topics. We should update the 2.8.2 and 2.9.2 branch's pulsar dependency first.

### 2.8.2 branch are using sn-pulsar v2.8.1.0 (should update to v2.8.2.0):

https://github.com/streamnative/pulsar/blob/v2.8.1.0/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java#L537-L542

### 2.9.2 branch are using sn-pulsar v2.9.0-rc-202110221101 (should update to v2.9.0):

https://github.com/streamnative/pulsar/blob/v2.9.0-rc-202110221101/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java#L523-L530

**Comment by BewareMyPower** [comment]
Could you rebase to branch-2.8.2?

**Comment by wenbingshen** [comment]
> Could you rebase to branch-2.8.2?

Addressed done. PTAL. Thanks.

**Review by Demogorgon314 — APPROVED** [review]

**Review by BewareMyPower — APPROVED** [review]

**Pull request merged**
