### PR TITLE
Add docs for Envoy proxy

### PR DESCRIPTION
**Pull request by BewareMyPower**

### CODE REVIEW

**Comment by Anonymitaet** [comment]
Hi @BewareMyPower thanks for your inputs, I've drafted one [here](https://docs.google.com/document/d/1WPaihtWxyFZNq0OiHKXOkiEb7RbgNSLretPuOYPPnMc/edit#), could you PTAL?

**Comment by BewareMyPower** [comment]
@Anonymitaet OK

**Comment by Anonymitaet** [comment]
@BewareMyPower I've updated the [doc](https://docs.google.com/document/d/1WPaihtWxyFZNq0OiHKXOkiEb7RbgNSLretPuOYPPnMc/edit#) based on our discussions, you can update the PR accordingly, thanks.

**Comment by BewareMyPower** [comment]
It's done. PTAL @Anonymitaet

**Review by Anonymitaet — APPROVED** [review]

**Review by Anonymitaet — APPROVED** [review]

**Pull request merged**
