### PR TITLE
Bump Pulsar to 2.11.0.0-rc3 and use JDK17 for KoP

### PR DESCRIPTION
**Pull request by BewareMyPower**
### Modifications

Upgrade `maven-shaded-plugin` to 3.4.0 because 3.2.4 seems not work with JDK 17.

> entry io/streamnative/kafka/client/zero/nine/Consumer009Impl.class: java.lang.IllegalArgumentException: Unsupported

Skip `__change_event` system topic when processing list topics request.

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by Demogorgon314 — DISMISSED** [review]

**Comment by Demogorgon314** [comment]
@BewareMyPower Look like some tests still fail.

**Comment by BewareMyPower** [comment]
@Demogorgon314 I've addressed them. It looks like Pulsar 2.11 has created `__changed_events` system topic so that the result of list topics are affected. I'm not sure why older versions don't have this issue.

**Comment by BewareMyPower** [comment]
There are still two failed tests left:

```
Error:  Failures: 
Error:    CacheInvalidatorTest.cleanup:111->KopProtocolHandlerTestBase.internalCleanup:319->KopProtocolHandlerTestBase.stopBroker:355->KopProtocolHandlerTestBase.stopBroker:351 » PulsarServer
Error:    TransactionWithOAuthBearerAuthTest.cleanup:72->TransactionTest.cleanup:77->KopProtocolHandlerTestBase.internalCleanup:319->KopProtocolHandlerTestBase.stopBroker:355->KopProtocolHandlerTestBase.stopBroker:351 » PulsarServer
```

**Comment by BewareMyPower** [comment]
@Demogorgon314 Now all tests passed.

**Review by Technoboy- — APPROVED** [review]

**Pull request merged**
