### PR TITLE
Complete the ProducerIdManager component

### PR DESCRIPTION
**Pull request by gaoran10**
Complete the ProducerIdManager component and add tests for it.

### CODE REVIEW

**Review by jiazhai — APPROVED** [review]

**Comment by jiazhai** [comment]
@BewareMyPower Would you please also help take a review?

**Review by BewareMyPower — APPROVED** [review]

**Comment by BewareMyPower** [comment]
The Codacy Static Code Analysis is weird.

> Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.
>> private int brokerId = 1;

Could you adjust the `brokerId` position and try again? If Codacy Static Code Analysis still failed, we'll just ignore it.

**Comment by jiazhai** [comment]
> The Codacy Static Code Analysis is weird.
> 
> > Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.
> > > private int brokerId = 1;
> 
> Could you adjust the `brokerId` position and try again? If Codacy Static Code Analysis still failed, we'll just ignore it.

@gaoran10 FYI

**Comment by gaoran10** [comment]
I found some methods before the field declarations, such as `getListeners()` and `getKafkaAdvertisedListeners()`, maybe we could adjust their positions, or ignored this code analysis problem.

**Comment by BewareMyPower** [comment]
@gaoran10 Yeah, you can adjust their positions. When these methods were added, the Codacy analysis was not enabled. And it seems that Codacy does only check the modified sources so that other PRs passed the tests.

**Pull request merged**
