### PR TITLE
Restore the support for Kafka clients 0.9 and 0.10

### PR DESCRIPTION
**Pull request by Demogorgon314**
Fixes: #1293

### Motivation

#1060 updates the `kafka-clients` dependency to 2.1.1 but it drops the support for Kafka clients 0.9 and 0.10 because `ListOffsetRequest.offsetData()` method has removed.

### Modifications

Add the old version of `ListOffsetRequest` to be compatible with Kafka clients 0.9 and 0.10.

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by eolivelli** [comment]
IIRC the main problem that was solved by https://github.com/streamnative/kop/pull/1060 is that older Kafka Clients bring well known CVEs inside the KOP package.
For that reason we had to drop it, otherwise KOP is not usable by enterprises that require 0 CVEs to run something in production.

This PR defeats the purpose of 1060.
I am not sure we can do this.

@nicoloboschi can you please confirm ?

**Comment by eolivelli** [comment]
an alternative approach is to copy/paste (or write from scratch) only the classes the we need

**Comment by Demogorgon314** [comment]
@eolivelli Sure,  I'll try to copy the necessary classes.

**Review by eolivelli — APPROVED** [review]
LGTM

great work

**Review by BewareMyPower — APPROVED** [review]

**Comment by woshihaoren** [comment]
@BewareMyPower why revert this pr ?
kop 2.10.6 can not work on 0.10.

**Comment by BewareMyPower** [comment]
@woshihaoren Both this PR and https://github.com/streamnative/kop/pull/1060 are reverted. https://github.com/streamnative/kop/pull/1060 breaks the compatibility with 0.9 and 1.0 clients and this PR restores the compatibility. Since both them are reverted, 2.10.1.6 should still be compatible with 0.9 and 1.0 clients.

Could you open an issue to verify KoP 2.10.1.6 cannot work for Kafka 0.10 client?

**Pull request merged**
