### PR TITLE
enable continuous offset for test

### PR DESCRIPTION
**Pull request by aloyszhang**
enable continuous offset for test

### CODE REVIEW

**Review by BewareMyPower — APPROVED** [review]

**Comment by BewareMyPower** [comment]
Does this PR need latest pulsar dependency? The tests failed at setup phase:

```
org.apache.pulsar.broker.PulsarServerException: java.lang.IllegalStateException
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:643)
	at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.startBroker(KopProtocolHandlerTestBase.java:312)
	at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.startBroker(KopProtocolHandlerTestBase.java:304)
	at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.init(KopProtocolHandlerTestBase.java:226)
	at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.internalSetup(KopProtocolHandlerTestBase.java:191)
	at io.streamnative.pulsar.handlers.kop.KafkaIntegrationTest.setup(KafkaIntegrationTest.java:172)
        ...
Caused by: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at io.streamnative.pulsar.handlers.kop.KafkaProtocolHandler.newChannelInitializers(KafkaProtocolHandler.java:272)
	at org.apache.pulsar.broker.protocol.ProtocolHandlerWithClassLoader.newChannelInitializers(ProtocolHandlerWithClassLoader.java:71)
	at org.apache.pulsar.broker.protocol.ProtocolHandlers.newChannelInitializers(ProtocolHandlers.java:124)
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:617)
	at org.apache.pulsar.broker.PulsarService$MockitoMock$680837022.start$accessor$U4VYq8i2(Unknown Source)
	at org.apache.pulsar.broker.PulsarService$MockitoMock$680837022$auxiliary$GNpZAo8J.call(Unknown Source)
        ...
```

**Comment by aloyszhang** [comment]
Yes, this problem can be resolved after https://github.com/apache/pulsar/pull/9088 merged.

**Comment by BewareMyPower** [comment]
@aloyszhang You can update pulsar version to 2.8.0-rc-202101042232 now.

**Comment by BewareMyPower** [comment]
Close this PR since it's contained in #296

**Pull request closed without merging**
