### PR TITLE
Fix import wrong authentication exception

### PR DESCRIPTION
**Pull request by Demogorgon314**
## Motivation
In PR #697 , used `javax.naming.AuthenticationException`, but should be `org.apache.kafka.common.errors.AuthenticationException`, otherwise will cause uncovered exception when throw `IllegalSaslStateException`.

## Modifications
Alter `javax.naming.AuthenticationException` to `org.apache.kafka.common.errors.AuthenticationException`.

### CODE REVIEW

**Review by wenbingshen — APPROVED** [review]
LGTM, this is my mistake, thanks for your fix it.

**Comment by wenbingshen** [comment]
@Demogorgon314 I saw `javax.naming.AuthenticationException` appearing in the following classes at the same time: `OauthValidatorCallbackHandler,` `PlainSaslServer,` `OauthLoginCallbackHandler,` should we unify Authentication exception types.

**Comment by wenbingshen** [comment]
@Demogorgon314 We should reuse `llegalStateException` which defined in [SaslAuthenticator](https://github.com/streamnative/kop/blob/master/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java#L94), PTAL :)

**Comment by Demogorgon314** [comment]
> @Demogorgon314 I saw `javax.naming.AuthenticationException` appearing in the following classes at the same time: `OauthValidatorCallbackHandler,` `PlainSaslServer,` `OauthLoginCallbackHandler,` should we unify Authentication exception types.

Agree. We should unify Authentication exception types.

**Review by BewareMyPower — APPROVED** [review]

**Pull request merged**
