### PR TITLE
lombok version is too low , Compilation failed

### PR DESCRIPTION
**Pull request by lordcheng10**

### CODE REVIEW

**Comment by BewareMyPower** [comment]
Could you add more explanations? What's the error?

**Comment by lordcheng10** [comment]
> Could you add more explanations? What's the error?

Related description here：https://github.com/streamnative/kop/issues/729，

> Could you add more explanations? What's the error?

The lombok version is too low and does not support java10 or above, execute the command: mvn -DskipTests package, an error is reported:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project pulsar-protocol-handler-kafka: Fatal error compiling: java.lang.ExceptionInInitializerError: Unable to make field private com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs accessible: module jdk.compiler does not "opens com.sun.tools.javac.processing" to unnamed module @1781a649 -> [Help 1]

Compile successfully after modifying the lombok version to 1.18.20。

**Comment by lordcheng10** [comment]
> > Could you add more explanations? What's the error?
> 
> Related description here：[https://github.com/streamnative/kop/issues/729，](https://github.com/streamnative/kop/issues/729%EF%BC%8C)
> 
> > Could you add more explanations? What's the error?
> 
> The lombok version is too low and does not support java10 or above, execute the command: mvn -DskipTests package, an error is reported:
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project pulsar-protocol-handler-kafka: Fatal error compiling: java.lang.ExceptionInInitializerError: Unable to make field private com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs accessible: module jdk.compiler does not "opens com.sun.tools.javac.processing" to unnamed module @1781a649 -> [Help 1]
> 
> Compile successfully after modifying the lombok version to 1.18.20。

I am using jdk11, do I need to use a lower version of jdk?

**Comment by lordcheng10** [comment]
> Could you add more explanations? What's the error?

Switch to jdk 11 to compile successfully, it was compiled with jdk8 before。

**Pull request closed without merging**
