### PR TITLE
[transactions] Implement transaction recovery

### PR DESCRIPTION
**Pull request by eolivelli**
### Motivation

Currently KOP is not fully recovering the status of transactions (the so called ProducerState in Kafka). 

### Modifications

Summary of changes:
- introduce a new system topic __transaction_producer_state that stores SNAPSHOTs of the state of the transactions for each partition
- implement recovery: start from the latest snapshot and read all the messages up to the tail of the topic
- implement removal of old Aborted Transactions
- recovery operations happen on a dedicated thread pool
- there is a configuration flag to turn off ProducerState recovery (in case that there are problems, the operation may take some time on big topics if there is no available snapshot)
- assign a kafkaTopicUUID property to the topics created using the Kafka API (admin or auto-create), this is needed to support delete/create workflows, because we cannot use the SNAPSHOT takes from the "old" life of a topic and apply it for the recovery of the "new life" of the topic. Topics created using Pulsar APIs work decently but it is not 100% safe (if we detect that the current position is smaller than the latest snapshot, so the snapshot seems to be taken in the future, ignore the snapshot and we start from the beginning of the topic)
- AppendRecordContext must not be recyclable 

This change also includes a few improvements to the Topic Lookup system that are needed in order to recover well from failure scenarios during transaction recovery:
- broker outages
- network failures to some components
- full k8s node failures (nodes that contain brokers or bookies for instance)

One interesting point that makes KOP better that Kafka is that in Kafka they store the data and the snapshots on the local disks of the brokers, with Pulsar all the support data (SNAPHOTs and TX status) is stored on Pulsar topics, so the system is far more resilient to problems)

### Verifying this change

This change added tests

### Documentation

Check the box below.

Need to update docs? 

- [x] `doc-required` 
  
 We will have to document the new system topic
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by eolivelli** [comment]
I am trying to fix the errors
Some tests like in KafkaTopicConsumerManagerTest behave differently in my fork, that is not based on StreamNative Pulsar fork (but on DataStax).
I have to understand the differences.

**Comment by eolivelli** [comment]
I am still working on fixing the tests...

**Comment by eolivelli** [comment]
@BewareMyPower @Demogorgon314 
these tests pass for me locally

some errors on DistributedClusterTest are related to how the LoadBalancer assigns the topics to the brokers, the test expects that they are assigned to different brokers

```
Error:  Failures: 
Error:    DistributedClusterTest.testMultiBrokerProduceAndConsumeNonPartitionedTopic » ThreadTimeout
Error:    DistributedClusterTest.testMultiBrokerUnloadReload:403 expected [2] but found [1]
Error:    DistributedClusterTest.testMutiBrokerAndCoordinator:315 expected [2] but found [1]
Error:    DistributedClusterTest.testOneBrokerShutdown:604 expected [2] but found [1]
Error:  io.streamnative.pulsar.handlers.kop.TransactionTest.testPurgeAbortedTx(io.streamnative.pulsar.handlers.kop.TransactionTest)
Error:    Run 1: TransactionTest.testPurgeAbortedTx:875->consumeTxnMessage:265 messages: [msg2, msg3, msg4, msg5, msg6] expected [3] but found [5]
[INFO]   Run 2: PASS
```

**Comment by BewareMyPower** [comment]
I see another failed test:

```
Run 1: TransactionTest.testPurgeAbortedTx:875->consumeTxnMessage:265 messages: [msg2, msg3, msg4, msg5, msg6] expected [3] but found [5]
```

**Comment by BewareMyPower** [comment]
It's better to split it to multiple PRs, which could be more friendly for review and tests.

**Comment by eolivelli** [comment]
@BewareMyPower I will try to split, no very easy. It will take some time

**Comment by eolivelli** [comment]
@BewareMyPower @Demogorgon314 
This is the first PR
https://github.com/streamnative/kop/pull/1720

I will send one PR at a time

**Comment by eolivelli** [comment]
I am closing this PR in order to reduce the noise

**Pull request closed without merging**
