### PR TITLE
#237 remove partition queue to improve performance

### PR DESCRIPTION
**Pull request by yuanboliu**

### CODE REVIEW

**Comment by BewareMyPower** [comment]
I think @jiazhai 's option in #237 is not to remove the queue.

This PR reverts #150 , so I think the performance improvement needs to be verified. Could you provide any performance comparison between before and after this fix?

Though from my perspective, `transQueue` is redundant because `persistentTopic.publishMessage` calls `ManagedLedger#asyncAddEntry` which is already an asynchronous operation.

**Comment by BewareMyPower** [comment]
In addition, I think it would be helpful to have @ltamber 's option.

**Comment by yuanboliu** [comment]
@BewareMyPower 
Thanks for your comments and sorry for late response.
After testing this pr in private envrionment, there is not much evidence showing this pr has huge performance improvements. I'll close this pr, go through our inner repo again and hope to come up with more prs for kop project.

**Comment by yuanboliu** [comment]
oops, seems I cannot close this pr.

**Comment by BewareMyPower** [comment]
Ok, let me close the PR.

**Pull request closed without merging**
