### PR TITLE
KafkaMessageOrderKafkaTest: prevent spammy logs due to wrong entry in Kafka format received by the Pulsar consumer

### LINKED ISSUE #464: [BUG] SingleMessageMetadata checkRequiredFields failed
**Describe the bug**

When processing fetch requests, following exception is thrown in server side

```
01:39:54.437 [pulsar-client-io-54-1:org.apache.pulsar.client.impl.ClientCnx@280] WARN  org.apache.pulsar.client.impl.ClientCnx - [localhost/127.0.0.1:15002] Got exception java.lang.IllegalStateException: Some required fields are missing
	at org.apache.pulsar.common.api.proto.SingleMessageMetadata.checkRequiredFields(SingleMessageMetadata.java:478)
	at org.apache.pulsar.common.api.proto.SingleMessageMetadata.parseFrom(SingleMessageMetadata.java:473)
	at org.apache.pulsar.common.protocol.Commands.deSerializeSingleMessageInBatch(Commands.java:1621)
	at org.apache.pulsar.client.impl.ConsumerImpl.receiveIndividualMessagesFromBatch(ConsumerImpl.java:1235)
	at org.apache.pulsar.client.impl.ConsumerImpl.messageReceived(ConsumerImpl.java:1066)
	at org.apache.pulsar.client.impl.ClientCnx.handleMessage(ClientCnx.java:446)
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:186)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
Run `KafkaMessageOrderKafkaTest#testKafkaProduceMessageOrder`, we can see a lot of exceptions, though the tests still passed.

**Expected behavior**
The exception should not be thrown.

### PR DESCRIPTION
**Pull request by eolivelli**
Fixes #464 

This patches prevent these errors in the logs:
```
22:10:10.220 [pulsar-client-io-35-1:org.apache.pulsar.client.impl.ClientCnx@282] WARN  org.apache.pulsar.client.impl.ClientCnx - [localhost/127.0.0.1:15002] Got exception java.lang.IllegalStateException: Some required fields are missing
	at org.apache.pulsar.common.api.proto.SingleMessageMetadata.checkRequiredFields(SingleMessageMetadata.java:478)
	at org.apache.pulsar.common.api.proto.SingleMessageMetadata.parseFrom(SingleMessageMetadata.java:473)
	at org.apache.pulsar.common.protocol.Commands.deSerializeSingleMessageInBatch(Commands.java:1635)
	at org.apache.pulsar.client.impl.ConsumerImpl.receiveIndividualMessagesFromBatch(ConsumerImpl.java:1257)
	at org.apache.pulsar.client.impl.ConsumerImpl.messageReceived(ConsumerImpl.java:1084)
	at org.apache.pulsar.client.impl.ClientCnx.handleMessage(ClientCnx.java:448)
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:186)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
```

### CODE REVIEW

**Review by BewareMyPower — APPROVED** [review]

**Comment by eolivelli** [comment]
@BewareMyPower on my CI this test is quite flaky.
I am investigating the reasons....
stay tuned

**Comment by BewareMyPower** [comment]
@eolivelli Did you mean `testDeletePartition`? I see it failed many times. For example: https://github.com/streamnative/kop/runs/5490424414?check_suite_focus=true

**Comment by eolivelli** [comment]
No, I mean "testKafkaProduceMessageOrder" with batch size = 200

**Comment by eolivelli** [comment]
but the test never fails on my laptop

**Comment by eolivelli** [comment]
for "testDeletePartition" I can take a look when I see it failing.

**Comment by eolivelli** [comment]
@BewareMyPower I started to debug testDeletePartition, I have seen an error on my CI.
I will keep you posted (and possibly send a fix)

**Comment by BewareMyPower** [comment]
I also found it's flaky and opened an issue: https://github.com/streamnative/kop/issues/1168

At now, this PR won't be cherry-picked to other branches.

**Pull request merged**
