### PR TITLE
collect publish rate

### LINKED ISSUE #284: [BUG] msgRateIn and msgThroughputIn is 0
**Describe the bug**
`msgRateIn ` and `msgThroughputIn ` is 0

**To Reproduce**
1. produce message use client.
2. get metrics to use command or grafana dashboard.

**Screenshots**
image

image

**Additional context**
After #228 be merged, `bytesInCounter` and `msgInCounter` is available, but `msgRateIn ` and `msgThroughputIn `  is update by `MessagePublishContext` in pulsar.

### PR DESCRIPTION
**Pull request by dockerzhang**
fixes #284

pulsar will add a `updateRates` method for this PR.

### CODE REVIEW

**Comment by dockerzhang** [comment]
need https://github.com/apache/pulsar/pull/9049 to be merged first.

**Comment by dockerzhang** [comment]
@BewareMyPower https://github.com/apache/pulsar/pull/9049 was merged, please update the dependency.

**Comment by BewareMyPower** [comment]
OK, we'll first wait for new sn-pulsar released. Then I'll provide a pulsar version and you can just update the dependency in your PR.

**Comment by BewareMyPower** [comment]
2.8.0-rc-202012272229

**Review by BewareMyPower — APPROVED** [review]
LGTM. Good job!

**Pull request merged**
