### PR TITLE
[bugfix][transactions] Release memory in TransactionMarkerChannelHandler

### PR DESCRIPTION
**Pull request by Demogorgon314**
### Motivation

Release memory in TransactionMarkerChannelHandler

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by Demogorgon314** [comment]
@eolivelli Please help review this PR, thanks!

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by BewareMyPower** [comment]
Do we need to add the `release/branch-2.10.4` tag?

**Review by BewareMyPower — APPROVED** [review]

**Pull request merged**
